routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('textareas', 'TextareaController');

Route::resource('listareas', 'ListareaController');

Route::resource('titleh2s', 'Titleh2Controller');

Route::resource('titleh1s', 'Titleh1Controller');

Route::resource('imgareas', 'ImgareaController');

Route::resource('titles', 'TitleController');
Route::resource('admin', 'TitleController');

app/Textarea.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Textarea extends Model
{
    protected $fillable = ['content', 'rank', 'idparent'];
}

app/Http/Controllers/TextareaController.php
<?php

namespace App\Http\Controllers;

use App\Textarea;
use App\Imgarea;
use Illuminate\Http\Request;

class TextareaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $textareas = Textarea::all();
        return view('textareas.index', compact('textareas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('textareas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'content' => 'required',
            'rank' => 'required',
            'idparent' => 'required'
        ]);

        Textarea::create($request->all());

        return redirect()->route('titles.index')->with('success', 'Text added sucessfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Textarea  $textarea
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $imgareas = Imgarea::where('idparent', '=', $id)->get();
        return view('imgareas.index', compact('imgareas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Textarea  $textarea
     * @return \Illuminate\Http\Response
     */
    public function edit(Textarea $textarea)
    {
        return view('textareas.edit', compact('textarea'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Textarea  $textarea
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Textarea $textarea)
    {
        $request->validate([
            'content' => 'required',
            'rank' => 'required'
        ]);

        $textarea->update($request->all());

        return redirect()->route('titles.index')->with('success', 'Text updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Textarea  $textarea
     * @return \Illuminate\Http\Response
     */
    public function destroy(Textarea $textarea)
    {
        $textarea->delete();
        return redirect()->route('titles.index')->with('success', 'Text deleted succesfully');
    }
}

resources/views/textareas/create.blade.php
@extends('textareas.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Text or Paragraph</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('textareas.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('textareas.store') }}" method="POST">
    @csrf

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Text:</strong>
                <textarea class="form-control" style="height:150px" name="content" placeholder="Content"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Rank:</strong>
                <input type="text" name="rank" class="form-control" placeholder="Rank">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Id Parent:</strong>
                <input type="text" name="idparent" class="form-control" placeholder="ID Parent">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/textareas/edit.blade.php
@extends('textareas.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Text</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('textareas.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('textareas.update',$textarea->id) }}" method="POST">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Text:</strong>
                <textarea class="form-control" style="height:150px" name="content" placeholder="Detail">{{ $textarea->content }}</textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Rank:</strong>
                <input type="text" name="rank" value="{{ $textarea->rank }}" class="form-control" placeholder="Rank">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>ID Parent:</strong>
                <input type="text" name="idparent" value="{{ $textarea->idparent }}" class="form-control" placeholder="ID Parent">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/textareas/index.blade.php
@extends('textareas.layout')

@section('content')
<div class="row" style="margin-bottom: 10px;">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Text for - ID parent</h2>
        </div>
    </div>
</div>

<div class="row" style="margin-bottom: 10px;">
    <div>
        <a class="btn btn-success" href="{{ route('textareas.create') }}"> Create New Text</a>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Content</th>
        <th>Rank</th>
        <th>Created at </th>
        <th>Updated at </th>
        <th width="280px">Action</th>
    </tr>
    @foreach ($textareas as $textarea)
    <tr>
        <td>{{ $textarea->id }}</td>
        <td>{{ $textarea->content }}</td>
        <td>{{ $textarea->rank }}</td>
        <td>{{ $textarea->created_at }}</td>
        <td>{{ $textarea->updated_at }}</td>

        <td>
            <form action="{{ route('textareas.destroy',$textarea->id) }}" method="POST">

                <a class="btn btn-info" href="{{ route('textareas.show',$textarea->id) }}">Show</a>

                <a class="btn btn-primary" href="{{ route('textareas.edit',$textarea->id) }}">Edit</a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>


@endsection

resources/views/textareas/layout.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Laravel 7 CRUD Application - Laravel Tutorial</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>

<body>

    <div class="container">
        @yield('content')
    </div>

</body>

</html>

resources/views/textareas/show.blade.php
@extends('textareas.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show Product</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('textareas.index') }}"> Back</a>
        </div>
    </div>
</div>
@endsection