routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('textareas', 'TextareaController');

Route::resource('listareas', 'ListareaController');

Route::resource('titleh2s', 'Titleh2Controller');

Route::resource('titleh1s', 'Titleh1Controller');

Route::resource('imgareas', 'ImgareaController');

Route::resource('titles', 'TitleController');
Route::resource('admin', 'TitleController');

app/Titleh1.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Titleh1 extends Model
{
    protected $fillable = ['content', 'rank', 'idparent'];
}

app/Http/Controllers/Titleh1Controller.php
<?php

namespace App\Http\Controllers;

use App\Titleh1;
use App\Titleh2;
use Illuminate\Http\Request;

class Titleh1Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $titleh1s = Titleh1::all();
        return view('titleh1s.index', compact('titleh1s'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('titleh1s.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'content' => 'required',
            'rank' => 'required',
            'idparent' => 'required'
        ]);

        Titleh1::create($request->all());

        return redirect()->route('titles.index')->with('success', 'H1 added sucessfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Titleh1  $titleh1
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $titleh2s = Titleh2::where('idparent', '=', $id)->get();
        return view('titleh2s.index', compact('titleh2s'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Titleh1  $titleh1
     * @return \Illuminate\Http\Response
     */
    public function edit(Titleh1 $titleh1)
    {
        return view('titleh1s.edit', compact('titleh1'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Titleh1  $titleh1
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Titleh1 $titleh1)
    {
        $request->validate([
            'content' => 'required',
            'rank' => 'required'
        ]);

        $titleh1->update($request->all());

        return redirect()->route('titles.index')->with('success', 'H1 updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Titleh1  $titleh1
     * @return \Illuminate\Http\Response
     */
    public function destroy(Titleh1 $titleh1)
    {
        $titleh1->delete();
        return redirect()->route('titles.index')->with('success', 'H1 deleted succesfully');
    }
}

resources/views/titleh1s/create.blade.php
@extends('titleh1s.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add h1</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('titleh1s.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('titleh1s.store') }}" method="POST">
    @csrf

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                <textarea class="form-control" style="height:150px" name="content" placeholder="Title"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Rank:</strong>
                <input type="text" name="rank" class="form-control" placeholder="Rank">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Id Parent:</strong>
                <input type="text" name="idparent" value="{{ id }}" class="form-control" placeholder="ID Parent"">
            </div>
        </div>
        <div class=" col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

</form>
@endsection

resources/views/titleh1s/edit.blade.php
@extends('titleh1s.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Text</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('titleh1s.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('titleh1s.update',$titleh1->id) }}" method="POST">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                <textarea class="form-control" style="height:150px" name="content" placeholder="Title">{{ $titleh1->content }}</textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Rank:</strong>
                <input type="text" name="rank" value="{{ $titleh1->rank }}" class="form-control" placeholder="Rank">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>ID Parent:</strong>
                <input type="text" name="idparent" value="{{ $titleh1->idparent }}" class="form-control" placeholder="ID Parent">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/titleh1s/index.blade.php
@extends('titleh1s.layout')

@section('content')
<div class="row" style="margin-bottom: 10px;">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>H1</h2>
        </div>
    </div>
</div>

<div class="row" style="margin-bottom: 10px;">
    <div>
        <a class="btn btn-success" href="{{ route('titleh1s.create') }}"> Create New H1</a>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Content</th>
        <th>Rank</th>
        <th>Created at </th>
        <th>Updated at </th>
        <th width="280px">Action</th>
    </tr>
    @foreach ($titleh1s as $titleh1)
    <tr>
        <td>{{ $titleh1->id }}</td>
        <td>{{ $titleh1->content }}</td>
        <td>{{ $titleh1->rank }}</td>
        <td>{{ $titleh1->created_at }}</td>
        <td>{{ $titleh1->updated_at }}</td>

        <td>
            <form action="{{ route('titleh1s.destroy',$titleh1->id) }}" method="POST">

                <a class="btn btn-info" href="{{ route('titleh1s.show',$titleh1->id) }}">Show</a>

                <a class="btn btn-primary" href="{{ route('titleh1s.edit',$titleh1->id) }}">Edit</a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>


@endsection

resources/views/titleh1s/layout.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Laravel 7 CRUD Application - Laravel Tutorial</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>

<body>

    <div class="container">
        @yield('content')
    </div>

</body>

</html>

resources/views/titleh1s/show.blade.php
@extends('titleh1s.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show Product</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('titleh1s.index') }}"> Back</a>
        </div>
    </div>
</div>
@endsection